#! /bin/bash

../../bin/env-clean.sh

export COMPOSITORY_CLOUDKEEPER_VERSION=1.6.0
export COMPOSITORY_CLOUDKEEPER_ONE_VERSION=1.3.0
export COMPOSITORY_CLOUDKEEPER_PROXY_ADDRESS=
export COMPOSITORY_CLOUDKEEPER_ONE_TEMPLATE_DIR=/srv/share/cloudkeeper-one-templates
export COMPOSITORY_CLOUDKEEPER_ONE_OPENNEBULA_ENDPOINT=https://carach5.ics.muni.cz:6443/RPC2
export COMPOSITORY_CLOUDKEEPER_ONE_OPENNEBULA_DATASTORES=warg-default-shared
