version: '3.3'
services:
  imagemaster-winterfell:
    image: misenko/imagemaster3000:latest
    command: ["--certificate=/run/secrets/cert.pem",  "--key=/run/secrets/key.pem", "--endpoint=http://webserver/winterfell/", "--definitions-repository=https://github.com/Misenko/imagemaster3000-definitions.git", "--definitions-branch=winterfell", "--image-list-path=/var/spool/imagemaster3000/imagemaster3000.list", "--image-list-identifier=imagemaster3000-winterfell", "--group=metacloud", "--debug"]
    volumes:
      - images-winterfell:/var/spool/imagemaster3000:Z
    depends_on:
      - webserver
    secrets:
      - cert.pem
      - key.pem
    deploy:
      restart_policy:
        condition: none
  imagemaster-kingslanding:
    image: misenko/imagemaster3000:latest
    command: ["--certificate=/run/secrets/cert.pem",  "--key=/run/secrets/key.pem", "--endpoint=http://webserver/kingslanding/", "--definitions-repository=https://github.com/Misenko/imagemaster3000-definitions.git", "--definitions-branch=kingslanding", "--image-list-path=/var/spool/imagemaster3000/imagemaster3000.list", "--image-list-identifier=imagemaster3000-kingslanding", "--group=metacloud", "--debug"]
    volumes:
      - images-kingslanding:/var/spool/imagemaster3000:Z
    depends_on:
      - webserver
    secrets:
      - cert.pem
      - key.pem
    deploy:
      restart_policy:
        condition: none
  webserver:
    image: linuxserver/nginx
    environment:
      PGID: 999
      PUID: 999
    volumes:
      - images-winterfell:/config/www/winterfell:ro
      - images-kingslanding:/config/www/kingslanding:ro
  cloudkeeper-winterfell:
    image: cloudkeeper/cloudkeeper:latest
    command: ["--image-lists=http://webserver/winterfell/imagemaster3000.list", "--remote-mode", "--nginx-binary=/usr/sbin/nginx", "--nginx-ip-address=cloudkeeper-winterfell", "--nginx-proxy-ip-address=${PROXY_IP_ADDRESS}", "--nginx-proxy-port=50505", "--backend-endpoint=cloudkeeper-one-winterfell:50051", "--formats=qcow2", "--debug"]
    ports:
      - "50505:50505"
    depends_on:
      - webserver
    deploy:
      restart_policy:
        condition: none
  cloudkeeper-one-winterfell:
    image: cloudkeeper/cloudkeeper-one:latest
    command: ["--listen-address=0.0.0.0:50051", "--identifier=cloudkeeper-winterfell", "--opennebula-endpoint=${OPENNEBULA_ENDPOINT}", "--no-opennebula-secret", "--opennebula-datastores=winterfell", "--opennebula-allow-remote-source", "--appliances-template-dir=/templates", "--debug"]
    environment:
      ONE_AUTH: /run/secrets/opennebula-test-auth
    volumes:
      - ${WINTERFELL_TEMPLATE_DIR}:/templates:ro
    secrets:
      - opennebula-test-auth
  cloudkeeper-kingslanding:
    image: cloudkeeper/cloudkeeper:latest
    command: ["--image-lists=http://webserver/kingslanding/imagemaster3000.list", "--remote-mode", "--nginx-binary=/usr/sbin/nginx", "--nginx-ip-address=cloudkeeper-kingslanding", "--nginx-proxy-ip-address=${PROXY_IP_ADDRESS}", "--nginx-proxy-port=60606", "--backend-endpoint=cloudkeeper-one-kingslanding:60061", "--formats=raw", "--debug"]
    ports:
      - "60606:50505"
    depends_on:
      - webserver
    deploy:
      restart_policy:
        condition: none
  cloudkeeper-one-kingslanding:
    image: cloudkeeper/cloudkeeper-one:latest
    command: ["--listen-address=0.0.0.0:60061", "--identifier=cloudkeeper-kingslanding", "--opennebula-endpoint=${OPENNEBULA_ENDPOINT}", "--no-opennebula-secret", "--opennebula-datastores=kingslanding", "--opennebula-allow-remote-source", "--appliances-template-dir=/templates", "--debug"]
    environment:
      ONE_AUTH: /run/secrets/opennebula-test-auth
    volumes:
      - ${KINGSLANDING_TEMPLATE_DIR}:/templates:ro
    secrets:
      - opennebula-test-auth
volumes:
  images-winterfell:
  images-kingslanding:
secrets:
  opennebula-test-auth:
    external: true
  cert.pem:
    external: true
  key.pem:
    external: true
